version: '3'


services:
  mongo:
      image: 'mongo'
      restart: always
      environment:
        - MONGODB_DATABASE=admin
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=root
      ports:
      - 27017:27017
      volumes:
        - data:/data/db


volumes:
  data:
